### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by tkhwang** [tkhwang/progress#25]
Error: Failed to launch the browser process!
2020-06-21T15:11:45.341082+00:00 app[web.1]: /app/packages/backend/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

```
2020-06-21T15:11:28.466412+00:00 app[web.1]: GET /v1/resource?interest=TypeScript 200 2337 - 926.138 ms
2020-06-21T15:11:28.470581+00:00 heroku[router]: at=info method=GET path="/v1/resource?interest=TypeScript" host=learn-in-public.herokuapp.com request_id=3404f54e-f9b6-43fe-93f6-c65c8f3e1526 fwd="218.237.62.2" dyno=web.1 connect=0ms service=932ms status=200 bytes=2579 protocol=https
2020-06-21T15:11:45.123070+00:00 heroku[router]: at=info method=OPTIONS path="/v1/url/info" host=learn-in-public.herokuapp.com request_id=b3ab3fd5-e254-45ba-84ac-9c48b7cd3a57 fwd="218.237.62.2" dyno=web.1 connect=1ms service=1ms status=204 bytes=315 protocol=https
2020-06-21T15:11:45.123006+00:00 app[web.1]: OPTIONS /v1/url/info 204 0 - 0.193 ms
2020-06-21T15:11:45.341074+00:00 app[web.1]: Error: Failed to launch the browser process!
2020-06-21T15:11:45.341082+00:00 app[web.1]: /app/packages/backend/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
2020-06-21T15:11:45.341083+00:00 app[web.1]: 
2020-06-21T15:11:45.341084+00:00 app[web.1]: 
2020-06-21T15:11:45.341085+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2020-06-21T15:11:45.341085+00:00 app[web.1]: 
2020-06-21T15:11:45.341085+00:00 app[web.1]:     at onClose (/app/packages/backend/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189:20)
2020-06-21T15:11:45.341086+00:00 app[web.1]:     at Interface.<anonymous> (/app/packages/backend/node_modules/puppeteer/lib/launcher/BrowserRunner.js:179:65)
2020-06-21T15:11:45.341086+00:00 app[web.1]:     at Interface.emit (events.js:327:22)
2020-06-21T15:11:45.341087+00:00 app[web.1]:     at Interface.EventEmitter.emit (domain.js:482:12)
2020-06-21T15:11:45.341087+00:00 app[web.1]:     at Interface.close (readline.js:416:8)
2020-06-21T15:11:45.341087+00:00 app[web.1]:     at Socket.onend (readline.js:194:10)
2020-06-21T15:11:45.341087+00:00 app[web.1]:     at Socket.emit (events.js:327:22)
2020-06-21T15:11:45.341121+00:00 app[web.1]:     at Socket.EventEmitter.emit (domain.js:482:12)
2020-06-21T15:11:45.341122+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1221:12)
2020-06-21T15:11:45.341123+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-21T15:11:46.278808+00:00 heroku[router]: at=info method=POST path="/v1/url/info" host=learn-in-public.herokuapp.com request_id=4f632f9a-8384-470a-bc26-40ba5f240fbd fwd="218.237.62.2" dyno=web.1 connect=0ms service=953ms status=201 bytes=2134 protocol=https
```

**Comment by tkhwang** [comment]
https://stackoverflow.com/a/52228855/2453632

**Comment by tkhwang** [comment]
https://stackoverflow.com/a/55090914/2453632

```
$ heroku buildpacks:clear
$ heroku buildpacks:add --index 1 https://github.com/jontewks/puppeteer-heroku-buildpack
$ heroku buildpacks:add --index 1 heroku/nodejs
```

```
const browser = await puppeteer.launch({
  'args' : [
    '--no-sandbox',
    '--disable-setuid-sandbox'
  ]
});
```
