### ISSUE TITLE
typrOrm configuration : DB not connected

### ISSUE THREAD

**Issue by tkhwang** [tkhwang/progress#3]
## Problem 

```
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/tkhwang/_tkhwang/repo/github/_tkhwang/progress/packages/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
```

**Comment by tkhwang** [comment]
* MySQL 8.X version 에서의 password 관련 설정으로 인한 문제
* AWS RDS version 을 5.7.X 로 설정하여 사용하도록 함.

**Comment by tkhwang** [comment]
* 실제 문제는 nest.js 에서 `.env` 값 참조가 되지 않아서 발생함.
* https://docs.nestjs.com/techniques/configuration 참조하여 적용함.
